---
title: "Instacart plots dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)
library(plotly)
```

# loading the data and filter the ones under the department 'alcohol'
```{r}
data("instacart")

instacart_df = 
  instacart %>% 
  filter(department == "alcohol")
```



Column {data-width=650}
-----------------------------------------------------------------------

### The number of orders in each aisle in 'alcohol' department

```{r}
instacart_df %>% 
  group_by(aisle) %>% 
  summarize(number_order = n()) %>% 
  mutate(aisle = fct_reorder(aisle, number_order)) %>% 
  plot_ly(x = ~aisle, y = ~number_order, color = ~aisle, type = "bar", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### The distribution of the days when the orders are placed in each aisle

```{r}
instacart_df %>% 
  rename(day_in_week = order_dow) %>% 
  plot_ly(x = ~aisle, y = ~ day_in_week, color = ~aisle, type = "box", colors = "viridis")
```

### The time(hour) in each day when the orders are placed in each aisle

```{r}
instacart_df %>% 
  group_by(aisle, order_hour_of_day) %>% 
  summarize(number_order = n()) %>% 
  plot_ly(x = ~order_hour_of_day, y = ~number_order, color = ~aisle, type = "scatter", mode = 'lines+markers', colors = "viridis")
  
```

