---
title: "Previous Experiences"
output: 
  html_document:
    toc: true
    toc_float: true
---
#### Education
- **Columbia University, Mailman School of Public Health (New York, NY)**
- *Master of Public Health, Epidemiology (Applied Biostatistics Certificate)*
- GPA: 4.07/4.3
- Relevant courses: *Applied Regression, Clinical Epidemiology, Data Science, Epidemiologic Analysis, Health Systems*

- **University of Toronto, Faculty of Arts and Science (Toronto, Canada)**
- *Bachelor of Science, Double Major in Biochemistry and Pharmacology (Sept 2018 – June 2022)*   
- GPA: 3.83/4.0
- Relevant courses: *Neuropsychopharmacology, Systems Pharmacology, Protein Homeostasis*


#### Skills
- **Computer Tools:** SAS, R, Microsoft Office Suite
- **SAS Modeling:** Linear Regression, Logistic Regression
- **Laboratory Skills:** Spectrophotometry, ELISA, PCR, Gel electrophoresis, Perfusion


#### Research Experience
- **Epidemiology of Parental Major Depression in the United States in 2021                   (New York, NY)**
- Conduct literature review by reading 40 journal articles to understand current research gaps and determine study aims.
- Analyze population demographic characteristics using SAS modeling from nationwide survey dataset.
- Present research results at 2023 Epidemiology master’s Student Day.

- **Endocannabinoid System on Parvalbumin Interneurons Under Stress (Toronto, Canada)**
- Conducted animal handling and suturing in stereotactic brain surgeries.
- Analyzed the engram cell connections using Imaris and experimental data with Prism.
- Completed final report to describe and interpret research results.

- **Manipulating Spatial Memory with Optogenetics (Toronto, Canada)**
- Performed animal behavioral tasks, mouse brain perfusion, and mouse brain slicing, with immunostaining and mounting on the brain slices for further analysis.
- Presented the research poster at the 2021 SickKids Summer Research Program Symposium Day.

- **In-vitro Test for Inflammasome Inhibitor (Hangzhou, China)**
- Performed ELISA to investigate the in-vitro activities of the inflammasome inhibitors.


#### Selected Course Project
- **Public Health Data Processing and Analyzing**, *Mar 2023*
- Processed and analyzed data related to public health issues (triglyceride level and alcohol use among patients) using SAS based on NHANES dataset.
- **The Pharmacology of Cannabidiol and Its Potential Therapeutic Effects**, *Nov 2021*
- Outlined the pharmacokinetics and pharmacodynamics of Cannabidiol (CBD), and its potential therapeutic effect in treating post-traumatic stress disorder (PTSD).



